// Generated by CoffeeScript 2.2.1
/*   eslint-disable import/first   */
var Header;

import {
  // ^^^ Required for React's Linter ^^^ #
  /*^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^*/
  Component
} from 'react';

import {
  PropTypes
} from 'prop-types';

import {
  Header as Base,
  Image,
  Segment
} from 'semantic-ui-react';

import {
  h
} from '@jhessin/react-hyperscript-helpers';

import '../styles/App.css';

Header = (function() {
  class Header extends Component {
    render() {
      return h(Segment, {
        inverted: true
      }, h(Base, {
        as: 'h2',
        textAlign: 'center',
        inverted: true,
        color: 'blue'
      }, h(Image, '.App-logo-spin', {
        centered: true,
        src: this.props.leftImage
      }), h(Image, '.App-plus', {
        centered: true,
        src: this.props.midImage
      }), h(Image, '.App-logo', {
        centered: true,
        src: this.props.rightImage
      })), h(Base, {
        as: 'h1',
        textAlign: 'center',
        inverted: true,
        color: 'blue'
      }, "Welcome to Databases!"));
    }

  };

  Header.propTypes = {
    leftImage: PropTypes.string.isRequired,
    midImage: PropTypes.string.isRequired,
    rightImage: PropTypes.string.isRequired
  };

  Header.defaultProps = {};

  Header.prototype.state = {};

  return Header;

}).call(this);

export {
  Header
};
