// Generated by CoffeeScript 2.2.1
/*   eslint-disable import/first   */
var Menu;

import {
  // ^^^ Required for React's Linter ^^^ #
  /*^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^*/
  Component
} from 'react';

import {
  PropTypes
} from 'prop-types';

import {
  Dropdown,
  Menu as Base
} from 'semantic-ui-react';

import {
  h
} from '@jhessin/react-hyperscript-helpers';

import {
  ModalCreateUser,
  ModalLogin,
  ModalLogout
} from './index';

Menu = (function() {
  class Menu extends Component {
    render() {
      var ref;
      return h(Base, {
        inverted: true
      }, h(Base.Item, h(Dropdown, {
        simple: true,
        text: (ref = this.props.userName) != null ? ref : 'User'
      }, h(Dropdown.Menu, h(ModalCreateUser, {
        render: function() {
          return h(Dropdown.Item, {
            text: 'Create'
          });
        }
      }), this.props.loggedIn ? h(ModalLogout, {
        render: function() {
          return h(Dropdown.Item, {
            text: 'Logout'
          });
        },
        onLogout: this.props.onLogout
      }) : h(ModalLogin, {
        render: function() {
          return h(Dropdown.Item, {
            text: 'Login'
          });
        },
        onLogin: this.props.onLogin
      })))));
    }

  };

  Menu.propTypes = {
    userName: PropTypes.string,
    loggedIn: PropTypes.bool.isRequired,
    onLogin: PropTypes.func.isRequired,
    onLogout: PropTypes.func.isRequired
  };

  Menu.defaultProps = {};

  Menu.prototype.state = {};

  return Menu;

}).call(this);

export {
  Menu
};
