// Generated by CoffeeScript 2.2.1
/*   eslint-disable import/first   */
var ModalCreateUser;

import {
  // ^^^ Required for React's Linter ^^^ #
  /*^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^*/
  Component
} from 'react';

import {
  PropTypes
} from 'prop-types';

import {
  Modal
} from 'semantic-ui-react';

import {
  h
} from '@jhessin/react-hyperscript-helpers';

ModalCreateUser = (function() {
  class ModalCreateUser extends Component {
    render() {
      return h(Modal, {
        trigger: this.props.render()
      }, h(Modal.Content, "This is the ModalCreateUser component"));
    }

  };

  ModalCreateUser.propTypes = {
    render: PropTypes.func.isRequired
  };

  ModalCreateUser.defaultProps = {
    render: function() {
      return h('div', 'Create User');
    }
  };

  ModalCreateUser.prototype.state = {};

  return ModalCreateUser;

}).call(this);

export {
  ModalCreateUser
};
