// Generated by CoffeeScript 2.2.1
/*   eslint-disable import/first   */
var ModalLogin;

import {
  // ^^^ Required for React's Linter ^^^ #
  /*^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^*/
  Component
} from 'react';

import {
  PropTypes
} from 'prop-types';

import {
  Modal,
  Button
} from 'semantic-ui-react';

import {
  h
} from '@jhessin/react-hyperscript-helpers';

ModalLogin = (function() {
  class ModalLogin extends Component {
    render() {
      return h(Modal, {
        trigger: this.props.render()
      }, h(Modal.Content, "This is the ModalLogin component"), h(Modal.Actions, h(Button, {
        onClick: () => {
          return this.props.onLogin();
        }
      }, 'Login')));
    }

  };

  ModalLogin.propTypes = {
    render: PropTypes.func.isRequired,
    onLogin: PropTypes.func.isRequired
  };

  ModalLogin.defaultProps = {
    render: function() {
      return h('p', 'ModalLogin');
    },
    onLogin: function() {}
  };

  ModalLogin.prototype.state = {};

  return ModalLogin;

}).call(this);

export {
  ModalLogin
};
