// Generated by CoffeeScript 2.2.1
/*   eslint-disable import/first   */
var App;

import {
  // ^^^ Required for React's Linter ^^^ #
  /*^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^*/
  Component
} from 'react';

import {
  // import { PropTypes } from 'prop-types'
  h
} from '@jhessin/react-hyperscript-helpers';

import {
  Grid
} from 'semantic-ui-react';

import {
  coffeeLogo,
  reactLogo,
  plusLogo
} from './images';

import {
  Header
} from './components';

App = (function() {
  class App extends Component {
    render() {
      return h(Grid, h(Grid.Column, h(Grid.Row, {
        stretched: true
      }, h(Header, {
        leftImage: reactLogo,
        midImage: plusLogo,
        rightImage: coffeeLogo
      }))));
    }

  };

  App.propTypes = {};

  App.defaultProps = {};

  App.prototype.state = {};

  return App;

}).call(this);

export default App;
