// Generated by CoffeeScript 2.2.1
import React from 'react';

import ReactDOM from 'react-dom';

import App from './App';

import {
  h
} from '@jhessin/react-hyperscript-helpers';

it('renders without crashing', function() {
  var div;
  div = document.createElement('div');
  ReactDOM.render(h(App), div);
  ReactDOM.unmountComponentAtNode(div);
});
