// Generated by CoffeeScript 2.2.1
/*   eslint-disable import/first   */
var App;

import {
  // ^^^ Required for React's Linter ^^^ #
  /*^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^*/
  Component
} from 'react';

import {
  // import { PropTypes } from 'prop-types'
  h
} from '@jhessin/react-hyperscript-helpers';

import {
  coffeeLogo,
  reactLogo,
  plusLogo
} from './images';

import {
  Header,
  Menu
} from './components';

App = (function() {
  class App extends Component {
    render() {
      return h('div', h(Header, {
        leftImage: reactLogo,
        midImage: plusLogo,
        rightImage: coffeeLogo
      }), h(Menu, {
        loggedIn: this.state.loggedIn,
        onLogin: () => {
          return this.setState({
            loggedIn: true
          });
        },
        onLogout: () => {
          return this.setState({
            loggedIn: false
          });
        }
      }));
    }

  };

  App.propTypes = {};

  App.defaultProps = {};

  App.prototype.state = {
    loggedIn: false
  };

  return App;

}).call(this);

export default App;
